### ISSUE TITLE
Potentially misleading documentation.

### ISSUE THREAD

**Issue by Billmike** [statelyai/docs#414]
Hi,

I was going through the docs on npm for the @xstate/react library and I ran into some errors trying out the sample code. So, the sample code is this shown below:

```js
import { useMachine } from '@xstate/react';
import { createMachine } from 'xstate';

const toggleMachine = createMachine({
  id: 'toggle',
  initial: 'inactive',
  states: {
    inactive: {
      on: { TOGGLE: 'active' }
    },
    active: {
      on: { TOGGLE: 'inactive' }
    }
  }
});

export const Toggler = () => {
  const [state, send] = useMachine(toggleMachine);

  return (
    <button onClick={() => send('TOGGLE')}>
      {state.value === 'inactive'
        ? 'Click to activate'
        : 'Active! Click to deactivate'}
    </button>
  );
};
```

This leads to the following errors in both my code and the console:

In VSCode:
![Screenshot 2024-03-15 at 09 59 42](https://github.com/statelyai/docs/assets/24798364/1577f343-6168-425c-a2ca-9b508e410e16)

The error in the browser console 👇 . The state doesn't get updated, and nothing happens in the UI:
![Screenshot 2024-03-15 at 10 00 21](https://github.com/statelyai/docs/assets/24798364/8d842b3d-7628-402b-bdea-db1256903621)

The issue happens to be that `send` requires an object rather than a string. The fix was to write the following code:
![Screenshot 2024-03-15 at 10 01 25](https://github.com/statelyai/docs/assets/24798364/e8825504-1ba9-4834-af75-6f415492751e)

**Recommendation**
The sample code to should updated to reflect the proper way of updating state with @xstate/react.

```js
import { useMachine } from '@xstate/react';
import { createMachine } from 'xstate';

const toggleMachine = createMachine({
  id: 'toggle',
  initial: 'inactive',
  states: {
    inactive: {
      on: { TOGGLE: 'active' }
    },
    active: {
      on: { TOGGLE: 'inactive' }
    }
  }
});

export const Toggler = () => {
  const [state, send] = useMachine(toggleMachine);

  return (
    <button onClick={() => send({ type: "TOGGLE" })}>
      {state.value === 'inactive'
        ? 'Click to activate'
        : 'Active! Click to deactivate'}
    </button>
  );
};
```

Package versions
```
@xstate/react: "^4.1.0"
@xstate: "^5.9.1"
```

**Comment by davidkpiano** [comment]
I updated them in the XState repo.

The official documentation is here: https://stately.ai/docs/xstate-react
