### ISSUE TITLE
Add Testing Section

### ISSUE THREAD

**Issue by MentalGear** [statelyai/docs#415]
Thank you for the great docs so far - but a crucial part is missing: testing!
Please provide best practices and a minimal example so we can use xState to the fullest: https://github.com/statelyai/docs/blob/main/docs/testing.mdx

**Comment by davidkpiano** [comment]
You're right! This is a good idea, and I will do it soon.

**Comment by davidkpiano** [comment]
https://stately.ai/docs/testing

**Comment by Fanoflix** [comment]
Any updates on the following?

![Image](https://github.com/user-attachments/assets/43a252d7-2372-48ba-865f-d58674c1779f)


Also, the docs for `@xstate/test` state that the utilities are moved into `@xstate/graph`. But I can't find `createTestModel` within the `@xstate/graph` package. Is it still under development?

I am new to xstate, so the questions above are not very well informed.
