### ISSUE TITLE
Opening collapsible nav heading opens currently visited page instead of clicked page

### ISSUE THREAD

**Issue by TobiObeck** [statelyai/docs#71]
I am on the page templates (https://stately.ai/docs/xstate/templates).

Middle mouse click or "right click > open in new tab" opens the current page in a new tab instead of the page that was clicked on.
You can see in the screenshot below that `#` is linked, so the current page. So instead a basics overview page or the first child item should be linked: xstate/basics/what-is-a-statechart

![image](https://user-images.githubusercontent.com/13554426/227355541-4ffbc5ca-2409-42d3-b57f-7259eb1e9d22.png)

I have never worked with docusaurus but tried a fix.

In `sidebars.js` I replaced 
```js
        {
          type: 'category',
          label: 'Basics',
          items: [
            'xstate/basics/what-is-a-statechart',
            'xstate/basics/options',
            'xstate/basics/inline-vs-named-options',
          ],
```

...with this

```js
        {
          type: 'category',
          label: 'Basics',
          link: {
            type: 'doc',
            id: 'xstate/basics/what-is-a-statechart',
          },
          items: [
            'xstate/basics/what-is-a-statechart',
            'xstate/basics/options',
            'xstate/basics/inline-vs-named-options',
          ],
        },
```
This seems to be working in principle but somehow creates another caret.
![image](https://user-images.githubusercontent.com/13554426/227371208-40603ff9-b3c3-4200-8313-4e4f949bade2.png)
I guess the custom.css needs to be adjusted in that case: https://github.com/statelyai/docs/blob/main/src/css/custom.css

**Comment by laurakalbag** [comment]
Oh wow, I didn’t even realise you could make the category heading into a useful link… this changes everything!

Thanks for your investigation into this, @TobiObeck. I’ll do some reorganising of the sidebar asap.

**Comment by TobiObeck** [comment]
My pleasure! Yep, I looked at how docusaurus themselves are doing it in their docs and peeked at their source code of [the sidebar](https://github.com/facebook/docusaurus/blob/main/website/sidebars.js) to see how they accomplish it. Also, looking at the TypeScript definitions of the sidebar (pressing <kbd>F12</kbd> in VS Code) was quite helpful to understand what kind of configuration is possible.

**Comment by TobiObeck** [comment]
@laurakalbag you are welcome! The overview pages did turn out great, good job! 🥳
